version: "2.2"

# global:
#   cap_add:
#     - NET_ADMIN
#     - SYS_ADMIN

x-stdsvc: &stdsvc
  image: iptfs
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.default.forwarding=1
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  devices:
    - /dev/net/tun:/dev/net/tun

services:
  dpdk1:
    <<: *stdsvc
    command: bash -c '/iptfs/run.sh -C -l -r 1000 10.0.0.10 -v'
    networks:
      unet:
        ipv4_address: 10.0.0.10
  dpdk2:
    <<: *stdsvc
    command: bash -c '/iptfs/run.sh -C -r 1000 10.0.0.10 -v'
    networks:
      unet:
        ipv4_address: 10.0.0.20
networks:
  unet:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.0.0/24
